# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  encoding: utf8
  database: myapp
  pool: 10
  username: root
  password: root
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: myapp_prod
  pool: 10
  username: root
  password: root
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: myapp_test
  pool: 10
  username: root
  password: root
  host: localhost